//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1q.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DevExp
    {
        public int Id { get; set; }
        public string Product_Name { get; set; }
        public string Vehicle_Name { get; set; }
        public string Driver_Name { get; set; }
        public string Gender { get; set; }
        public string Items { get; set; }
        public string Location { get; set; }
        public Nullable<decimal> Departure_Time { get; set; }
        public Nullable<decimal> Arrival_Time { get; set; }
    }
}
